name: deploy sensor

on:
  workflow_dispatch: 
    branches: [ production, develop ]
    paths: [ sensor/** ]

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sensor
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Docker image
        run: docker build -t ekhorn/litr:latest -f dockerfile .

      - name: Docker image info
        run: docker images

      - name: Push Docker image
        run: docker push ekhorn/litr:latest
